matrix:
  include:
    # Frontend
    - language: node_js
      node_js: 8.13.0
      before_install:
        - cd frontend
      install: yarn
      script:
        - yarn run lint
        - yarn run tsc
    # Backend
    - language: python
      python: 3.6
      before_install:
        - cd backend/
        - cp .env.example .env
      env:
        - CROWD_FUND_URL=https://eip-712.herokuapp.com/contract/crowd-fund CROWD_FUND_FACTORY_URL=https://eip-712.herokuapp.com/contract/factory
      install: pip install -r requirements/dev.txt
      script:
        - flask test
    # Contracts
    - language: node_js
      node_js: 8.13.0
      before_install:
        - cd contract/
      install: yarn && yarn add global truffle ganache-cli@6.1.8
      before_script:
        - ganache-cli > /dev/null &
        - sleep 10
      script:
        - yarn run test
      env:
        - CROWD_FUND_URL=https://eip-712.herokuapp.com/contract/crowd-fund
          CROWD_FUND_FACTORY_URL=https://eip-712.herokuapp.com/contract/factory
