matrix:
  include:
    # Frontend
    - language: node_js
      node_js: 8.13.0
      before_install:
        - cd frontend
      install: yarn
      script:
        - yarn run lint
        - yarn run tsc
    # Backend
    - language: python
      python: 3.6
      before_install:
        - cd backend/
        - cp .env.example .env
      install: pip install -r requirements/dev.txt
      script:
        - flask test
