import { User } from 'types';

export enum REVISION_CHANGE_TYPES {
  PROPOSAL_EDIT_BRIEF = 'PROPOSAL_EDIT_BRIEF',
  PROPOSAL_EDIT_CONTENT = 'PROPOSAL_EDIT_CONTENT',
  PROPOSAL_EDIT_TARGET = 'PROPOSAL_EDIT_TARGET',
  PROPOSAL_EDIT_TITLE = 'PROPOSAL_EDIT_TITLE',
  MILESTONE_ADD = 'MILESTONE_ADD',
  MILESTONE_REMOVE = 'MILESTONE_REMOVE',
  MILESTONE_EDIT_AMOUNT = 'MILESTONE_EDIT_AMOUNT',
  MILESTONE_EDIT_DAYS = 'MILESTONE_EDIT_DAYS',
  MILESTONE_EDIT_IMMEDIATE_PAYOUT = 'MILESTONE_EDIT_IMMEDIATE_PAYOUT',
  MILESTONE_EDIT_PERCENT = 'MILESTONE_EDIT_PERCENT',
  MILESTONE_EDIT_CONTENT = 'MILESTONE_EDIT_CONTENT',
}

export type RevisionChange = {
  type: REVISION_CHANGE_TYPES;
  milestoneIndex?: number;
};

export interface Revision {
  parentProposalId: string;
  parentRevisionId: string;
  revisionId: string;
  revisionIndex: number;
  changes: RevisionChange[];
  dateCreated: number;
  author: User;
}
