enum rfpTypes {
    FETCH_RFPS = 'FETCH_RFPS',
    FETCH_RFPS_FULFILLED = 'FETCH_RFPS_FULFILLED',
    FETCH_RFPS_REJECTED = 'FETCH_RFPS_REJECTED',
    FETCH_RFPS_PENDING = 'FETCH_RFPS_PENDING',
  
    FETCH_RFP = 'FETCH_RFP',
    FETCH_RFP_FULFILLED = 'FETCH_RFP_FULFILLED',
    FETCH_RFP_REJECTED = 'FETCH_RFP_REJECTED',
    FETCH_RFP_PENDING = 'FETCH_RFP_PENDING',
  }
  
  export default rfpTypes;
  