enum proposalTypes {
  PROPOSALS_DATA = 'PROPOSALS_DATA',
  PROPOSALS_DATA_FULFILLED = 'PROPOSALS_DATA_FULFILLED',
  PROPOSALS_DATA_REJECTED = 'PROPOSALS_DATA_REJECTED',
  PROPOSALS_DATA_PENDING = 'PROPOSALS_DATA_PENDING',

  PROPOSAL_DATA = 'PROPOSAL_DATA',
  PROPOSAL_DATA_FULFILLED = 'PROPOSAL_DATA_FULFILLED',
  PROPOSAL_DATA_REJECTED = 'PROPOSAL_DATA_REJECTED',
  PROPOSAL_DATA_PENDING = 'PROPOSAL_DATA_PENDING',

  PROPOSAL_COMMENTS = 'PROPOSAL_COMMENTS',
  PROPOSAL_COMMENTS_FULFILLED = 'PROPOSAL_COMMENTS_FULFILLED',
  PROPOSAL_COMMENTS_REJECTED = 'PROPOSAL_COMMENTS_REJECTED',
  PROPOSAL_COMMENTS_PENDING = 'PROPOSAL_COMMENTS_PENDING',

  PROPOSAL_UPDATES = 'PROPOSAL_UPDATES',
  PROPOSAL_UPDATES_FULFILLED = 'PROPOSAL_UPDATES_FULFILLED',
  PROPOSAL_UPDATES_REJECTED = 'PROPOSAL_UPDATES_REJECTED',
  PROPOSAL_UPDATES_PENDING = 'PROPOSAL_UPDATES_PENDING',

  PROPOSAL_CONTRIBUTIONS = 'PROPOSAL_CONTRIBUTIONS',
  PROPOSAL_CONTRIBUTIONS_FULFILLED = 'PROPOSAL_CONTRIBUTIONS_FULFILLED',
  PROPOSAL_CONTRIBUTIONS_REJECTED = 'PROPOSAL_CONTRIBUTIONS_REJECTED',
  PROPOSAL_CONTRIBUTIONS_PENDING = 'PROPOSAL_CONTRIBUTIONS_PENDING',

  POST_PROPOSAL_COMMENT = 'POST_PROPOSAL_COMMENT',
  POST_PROPOSAL_COMMENT_FULFILLED = 'POST_PROPOSAL_COMMENT_FULFILLED',
  POST_PROPOSAL_COMMENT_REJECTED = 'POST_PROPOSAL_COMMENT_REJECTED',
  POST_PROPOSAL_COMMENT_PENDING = 'POST_PROPOSAL_COMMENT_PENDING',

  POST_PROPOSAL_CONTRIBUTION = 'POST_PROPOSAL_CONTRIBUTION',
}

export default proposalTypes;
