enum proposalTypes {
  PROPOSALS_DATA = 'PROPOSALS_DATA',
  PROPOSALS_DATA_FULFILLED = 'PROPOSALS_DATA_FULFILLED',
  PROPOSALS_DATA_REJECTED = 'PROPOSALS_DATA_REJECTED',
  PROPOSALS_DATA_PENDING = 'PROPOSALS_DATA_PENDING',

  PROPOSAL_DATA = 'PROPOSAL_DATA',
  PROPOSAL_DATA_FULFILLED = 'PROPOSAL_DATA_FULFILLED',
  PROPOSAL_DATA_REJECTED = 'PROPOSAL_DATA_REJECTED',
  PROPOSAL_DATA_PENDING = 'PROPOSAL_DATA_PENDING',

  PROPOSAL_COMMENTS = 'PROPOSAL_COMMENTS',
  PROPOSAL_COMMENTS_FULFILLED = 'PROPOSAL_COMMENTS_FULFILLED',
  PROPOSAL_COMMENTS_REJECTED = 'PROPOSAL_COMMENTS_REJECTED',
  PROPOSAL_COMMENTS_PENDING = 'PROPOSAL_COMMENTS_PENDING',

  PROPOSAL_UPDATES = 'PROPOSAL_UPDATES',
  PROPOSAL_UPDATES_FULFILLED = 'PROPOSAL_UPDATES_FULFILLED',
  PROPOSAL_UPDATES_REJECTED = 'PROPOSAL_UPDATES_REJECTED',
  PROPOSAL_UPDATES_PENDING = 'PROPOSAL_UPDATES_PENDING',

  PROPOSAL_CONTRIBUTIONS = 'PROPOSAL_CONTRIBUTIONS',
  PROPOSAL_CONTRIBUTIONS_FULFILLED = 'PROPOSAL_CONTRIBUTIONS_FULFILLED',
  PROPOSAL_CONTRIBUTIONS_REJECTED = 'PROPOSAL_CONTRIBUTIONS_REJECTED',
  PROPOSAL_CONTRIBUTIONS_PENDING = 'PROPOSAL_CONTRIBUTIONS_PENDING',

  POST_PROPOSAL_COMMENT = 'POST_PROPOSAL_COMMENT',
  POST_PROPOSAL_COMMENT_FULFILLED = 'POST_PROPOSAL_COMMENT_FULFILLED',
  POST_PROPOSAL_COMMENT_REJECTED = 'POST_PROPOSAL_COMMENT_REJECTED',
  POST_PROPOSAL_COMMENT_PENDING = 'POST_PROPOSAL_COMMENT_PENDING',

  POST_PROPOSAL_CONTRIBUTION = 'POST_PROPOSAL_CONTRIBUTION',

  SET_PROPOSAL_PAGE = 'SET_PROPOSAL_PAGE',

  PROPOSAL_PAYOUT_REQUEST = 'PROPOSAL_PAYOUT_REQUEST',
  PROPOSAL_PAYOUT_REQUEST_FULFILLED = 'PROPOSAL_PAYOUT_REQUEST_FULFILLED',
  PROPOSAL_PAYOUT_REQUEST_REJECTED = 'PROPOSAL_PAYOUT_REQUEST_REJECTED',
  PROPOSAL_PAYOUT_REQUEST_PENDING = 'PROPOSAL_PAYOUT_REQUEST_PENDING',

  PROPOSAL_PAYOUT_REJECT = 'PROPOSAL_PAYOUT_REJECT',
  PROPOSAL_PAYOUT_REJECT_FULFILLED = 'PROPOSAL_PAYOUT_REJECT_FULFILLED',
  PROPOSAL_PAYOUT_REJECT_REJECTED = 'PROPOSAL_PAYOUT_REJECT_REJECTED',
  PROPOSAL_PAYOUT_REJECT_PENDING = 'PROPOSAL_PAYOUT_REJECT_PENDING',

  PROPOSAL_PAYOUT_ACCEPT = 'PROPOSAL_PAYOUT_ACCEPT',
  PROPOSAL_PAYOUT_ACCEPT_FULFILLED = 'PROPOSAL_PAYOUT_ACCEPT_FULFILLED',
  PROPOSAL_PAYOUT_ACCEPT_REJECTED = 'PROPOSAL_PAYOUT_ACCEPT_REJECTED',
  PROPOSAL_PAYOUT_ACCEPT_PENDING = 'PROPOSAL_PAYOUT_ACCEPT_PENDING',

  REPORT_PROPOSAL_COMMENT = 'REPORT_PROPOSAL_COMMENT',
  REPORT_PROPOSAL_COMMENT_PENDING = 'REPORT_PROPOSAL_COMMENT_PENDING',
  REPORT_PROPOSAL_COMMENT_FULFILLED = 'REPORT_PROPOSAL_COMMENT_FULFILLED',
  REPORT_PROPOSAL_COMMENT_REJECTED = 'REPORT_PROPOSAL_COMMENT_REJECTED',

  UPDATE_PROPOSAL_COMMENT = 'UPDATE_PROPOSAL_COMMENT',
}

export default proposalTypes;
