enum UsersActions {
  FETCH_USER = 'FETCH_USER',
  FETCH_USER_PENDING = 'FETCH_USER_PENDING',
  FETCH_USER_FULFILLED = 'FETCH_USER_FULFILLED',
  FETCH_USER_REJECTED = 'FETCH_USER_REJECTED',

  UPDATE_USER = 'UPDATE_USER',
  UPDATE_USER_PENDING = 'UPDATE_USER_PENDING',
  UPDATE_USER_FULFILLED = 'UPDATE_USER_FULFILLED',
  UPDATE_USER_REJECTED = 'UPDATE_USER_REJECTED',

  FETCH_USER_INVITES = 'FETCH_USER_INVITES',
  FETCH_USER_INVITES_PENDING = 'FETCH_USER_INVITES_PENDING',
  FETCH_USER_INVITES_FULFILLED = 'FETCH_USER_INVITES_FULFILLED',
  FETCH_USER_INVITES_REJECTED = 'FETCH_USER_INVITES_REJECTED',

  RESPOND_TO_INVITE = 'RESPOND_TO_INVITE',
  RESPOND_TO_INVITE_PENDING = 'RESPOND_TO_INVITE_PENDING',
  RESPOND_TO_INVITE_FULFILLED = 'RESPOND_TO_INVITE_FULFILLED',
  RESPOND_TO_INVITE_REJECTED = 'RESPOND_TO_INVITE_REJECTED',
}

export default UsersActions;
