enum UsersActions {
  FETCH_USER = 'FETCH_USER',
  FETCH_USER_PENDING = 'FETCH_USER_PENDING',
  FETCH_USER_FULFILLED = 'FETCH_USER_FULFILLED',
  FETCH_USER_REJECTED = 'FETCH_USER_REJECTED',

  UPDATE_USER = 'UPDATE_USER',
  UPDATE_USER_PENDING = 'UPDATE_USER_PENDING',
  UPDATE_USER_FULFILLED = 'UPDATE_USER_FULFILLED',
  UPDATE_USER_REJECTED = 'UPDATE_USER_REJECTED',

  FETCH_USER_CREATED = 'FETCH_USER_CREATED',
  FETCH_USER_CREATED_PENDING = 'FETCH_USER_CREATED_PENDING',
  FETCH_USER_CREATED_FULFILLED = 'FETCH_USER_CREATED_FULFILLED',
  FETCH_USER_CREATED_REJECTED = 'FETCH_USER_CREATED_REJECTED',

  FETCH_USER_FUNDED = 'FETCH_USER_FUNDED',
  FETCH_USER_FUNDED_PENDING = 'FETCH_USER_FUNDED_PENDING',
  FETCH_USER_FUNDED_FULFILLED = 'FETCH_USER_FUNDED_FULFILLED',
  FETCH_USER_FUNDED_REJECTED = 'FETCH_USER_FUNDED_REJECTED',

  FETCH_USER_COMMENTS = 'FETCH_USER_COMMENTS',
  FETCH_USER_COMMENTS_PENDING = 'FETCH_USER_COMMENTS_PENDING',
  FETCH_USER_COMMENTS_FULFILLED = 'FETCH_USER_COMMENTS_FULFILLED',
  FETCH_USER_COMMENTS_REJECTED = 'FETCH_USER_COMMENTS_REJECTED',
}

export default UsersActions;
