enum CreateTypes {
  UPDATE_FORM = 'UPDATE_FORM',

  INITIALIZE_FORM = 'INITIALIZE_FORM',
  INITIALIZE_FORM_PENDING = 'INITIALIZE_FORM_PENDING',
  INITIALIZE_FORM_FULFILLED = 'INITIALIZE_FORM_FULFILLED',
  INITIALIZE_FORM_REJECTED = 'INITIALIZE_FORM_REJECTED',

  SAVE_DRAFT = 'SAVE_DRAFT',
  SAVE_DRAFT_PENDING = 'SAVE_DRAFT_PENDING',
  SAVE_DRAFT_FULFILLED = 'SAVE_DRAFT_FULFILLED',
  SAVE_DRAFT_REJECTED = 'SAVE_DRAFT_REJECTED',

  FETCH_DRAFTS = 'FETCH_DRAFTS',
  FETCH_DRAFTS_PENDING = 'FETCH_DRAFTS_PENDING',
  FETCH_DRAFTS_FULFILLED = 'FETCH_DRAFTS_FULFILLED',
  FETCH_DRAFTS_REJECTED = 'FETCH_DRAFTS_REJECTED',

  CREATE_DRAFT = 'CREATE_DRAFT',
  CREATE_DRAFT_PENDING = 'CREATE_DRAFT_PENDING',
  CREATE_DRAFT_FULFILLED = 'CREATE_DRAFT_FULFILLED',
  CREATE_DRAFT_REJECTED = 'CREATE_DRAFT_REJECTED',

  DELETE_DRAFT = 'DELETE_DRAFT',
  DELETE_DRAFT_PENDING = 'DELETE_DRAFT_PENDING',
  DELETE_DRAFT_FULFILLED = 'DELETE_DRAFT_FULFILLED',
  DELETE_DRAFT_REJECTED = 'DELETE_DRAFT_REJECTED',

  SUBMIT_PROPOSAL = 'SUBMIT_PROPOSAL',
  SUBMIT_PROPOSAL_PENDING = 'SUBMIT_PROPOSAL_PENDING',
  SUBMIT_PROPOSAL_FULFILLED = 'SUBMIT_PROPOSAL_FULFILLED',
  SUBMIT_PROPOSAL_REJECTED = 'SUBMIT_PROPOSAL_REJECTED',

  // TODO - remove if not used (depending on design choices)
  // PUBLISH_PROPOSAL = 'PUBLISH_PROPOSAL',
  // PUBLISH_PROPOSAL_PENDING = 'PUBLISH_PROPOSAL_PENDING',
  // PUBLISH_PROPOSAL_FULFILLED = 'PUBLISH_PROPOSAL_FULFILLED',
  // PUBLISH_PROPOSAL_REJECTED = 'PUBLISH_PROPOSAL_REJECTED',
}

export interface CreateDraftOptions {
  redirect?: boolean;
}

export default CreateTypes;
