enum CreateTypes {
  UPDATE_FORM = 'UPDATE_FORM',

  RESET_FORM = 'RESET_FORM',

  SAVE_DRAFT = 'SAVE_DRAFT',
  SAVE_DRAFT_PENDING = 'SAVE_DRAFT_PENDING',
  SAVE_DRAFT_FULFILLED = 'SAVE_DRAFT_FULFILLED',
  SAVE_DRAFT_REJECTED = 'SAVE_DRAFT_REJECTED',

  FETCH_DRAFT = 'FETCH_DRAFT',
  FETCH_DRAFT_PENDING = 'FETCH_DRAFT_PENDING',
  FETCH_DRAFT_FULFILLED = 'FETCH_DRAFT_FULFILLED',
  FETCH_DRAFT_REJECTED = 'FETCH_DRAFT_REJECTED',

  SUBMIT = 'CREATE_PROPOSAL',
  SUBMIT_PENDING = 'CREATE_PROPOSAL_PENDING',
  SUBMIT_FULFILLED = 'CREATE_PROPOSAL_FULFILLED',
  SUBMIT_REJECTED = 'CREATE_PROPOSAL_REJECTED',
}

export default CreateTypes;
