enum CreateTypes {
  UPDATE_FORM = 'UPDATE_FORM',

  INITIALIZE_FORM = 'INITIALIZE_FORM',
  INITIALIZE_FORM_PENDING = 'INITIALIZE_FORM_PENDING',
  INITIALIZE_FORM_FULFILLED = 'INITIALIZE_FORM_FULFILLED',
  INITIALIZE_FORM_REJECTED = 'INITIALIZE_FORM_REJECTED',

  SAVE_DRAFT = 'SAVE_DRAFT',
  SAVE_DRAFT_PENDING = 'SAVE_DRAFT_PENDING',
  SAVE_DRAFT_FULFILLED = 'SAVE_DRAFT_FULFILLED',
  SAVE_DRAFT_REJECTED = 'SAVE_DRAFT_REJECTED',

  FETCH_DRAFTS = 'FETCH_DRAFTS',
  FETCH_DRAFTS_PENDING = 'FETCH_DRAFTS_PENDING',
  FETCH_DRAFTS_FULFILLED = 'FETCH_DRAFTS_FULFILLED',
  FETCH_DRAFTS_REJECTED = 'FETCH_DRAFTS_REJECTED',

  CREATE_DRAFT = 'CREATE_DRAFT',
  CREATE_DRAFT_PENDING = 'CREATE_DRAFT_PENDING',
  CREATE_DRAFT_FULFILLED = 'CREATE_DRAFT_FULFILLED',
  CREATE_DRAFT_REJECTED = 'CREATE_DRAFT_REJECTED',

  FETCH_AND_CREATE_DRAFTS = 'FETCH_AND_CREATE_DRAFTS',

  DELETE_DRAFT = 'DELETE_DRAFT',
  DELETE_DRAFT_PENDING = 'DELETE_DRAFT_PENDING',
  DELETE_DRAFT_FULFILLED = 'DELETE_DRAFT_FULFILLED',
  DELETE_DRAFT_REJECTED = 'DELETE_DRAFT_REJECTED',

  SUBMIT_PROPOSAL = 'SUBMIT_PROPOSAL',
  SUBMIT_PROPOSAL_PENDING = 'SUBMIT_PROPOSAL_PENDING',
  SUBMIT_PROPOSAL_FULFILLED = 'SUBMIT_PROPOSAL_FULFILLED',
  SUBMIT_PROPOSAL_REJECTED = 'SUBMIT_PROPOSAL_REJECTED',

  UNLINK_PROPOSAL_RFP = 'UNLINK_PROPOSAL_RFP',
  UNLINK_PROPOSAL_RFP_PENDING = 'UNLINK_PROPOSAL_RFP_PENDING',
  UNLINK_PROPOSAL_RFP_FULFILLED = 'UNLINK_PROPOSAL_RFP_FULFILLED',
  UNLINK_PROPOSAL_RFP_REJECTED = 'UNLINK_PROPOSAL_RFP_REJECTED',
}

export interface CreateDraftOptions {
  rfpId?: number;
  redirect?: boolean;
}

export default CreateTypes;
