"""add proposal contribution_bounty & rfp_opt_in

Revision ID: 13365ffe910e
Revises: 332a15eba9d8
Create Date: 2019-02-28 19:41:42.215923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13365ffe910e'
down_revision = '332a15eba9d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal', sa.Column('contribution_bounty', sa.String(
        length=255), server_default=sa.text("'0'"), nullable=False))
    op.add_column('proposal', sa.Column('rfp_opt_in', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposal', 'rfp_opt_in')
    op.drop_column('proposal', 'contribution_bounty')
    # ### end Alembic commands ###
