"""empty message

Revision ID: 1e1460456ce4
Revises: c55f96720196
Create Date: 2019-11-21 20:36:37.504400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e1460456ce4'
down_revision = 'c55f96720196'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rfp', sa.Column('version', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rfp', 'version')
    # ### end Alembic commands ###
