"""user banned & silenced fields

Revision ID: 27975c4a04a4
Revises: d39bb526eef4
Create Date: 2019-02-14 10:30:47.596818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27975c4a04a4'
down_revision = 'd39bb526eef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('banned', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('banned_reason', sa.String(), nullable=True))
    op.add_column('user', sa.Column('silenced', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'silenced')
    op.drop_column('user', 'banned_reason')
    op.drop_column('user', 'banned')
    # ### end Alembic commands ###
