"""empty message

Revision ID: 2f30fb7d656e
Revises: 3ffceaeb996a
Create Date: 2019-01-04 13:31:32.851145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f30fb7d656e'
down_revision = '3ffceaeb996a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal', sa.Column('date_approved', sa.DateTime(), nullable=True))
    op.add_column('proposal', sa.Column('date_published', sa.DateTime(), nullable=True))
    op.add_column('proposal', sa.Column('reject_reason', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposal', 'reject_reason')
    op.drop_column('proposal', 'date_published')
    op.drop_column('proposal', 'date_approved')
    # ### end Alembic commands ###
