"""empty message

Revision ID: 310dca400b81
Revises: fa1fedf4ca08
Create Date: 2019-02-05 11:24:11.291158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '310dca400b81'
down_revision = 'fa1fedf4ca08'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal', sa.Column('arbiter_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'proposal', 'user', ['arbiter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proposal', type_='foreignkey')
    op.drop_column('proposal', 'arbiter_id')
    # ### end Alembic commands ###
