"""empty message

Revision ID: 312db8611967
Revises: 95e93ff98cba
Create Date: 2018-11-06 11:07:33.205401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '312db8611967'
down_revision = '95e93ff98cba'
branch_labels = None
depends_on = None


def upgrade():
    # custom alter_column
    with op.batch_alter_table('proposal') as bop:
        bop.alter_column('proposal_id', new_column_name='proposal_address')
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('proposal', sa.Column('proposal_address', sa.String(length=255), nullable=False))
    # op.create_unique_constraint(None, 'proposal', ['proposal_address'])
    # op.drop_column('proposal', 'proposal_id')
    # ### end Alembic commands ###


def downgrade():
    # custom alter_column
    with op.batch_alter_table('proposal') as bop:
        bop.alter_column('proposal_address', new_column_name='proposal_id')
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('proposal', sa.Column('proposal_id', sa.VARCHAR(length=255), nullable=False))
    # op.drop_constraint(None, 'proposal', type_='unique')
    # op.drop_column('proposal', 'proposal_address')
    # ### end Alembic commands ###
