"""Add staking boolean column to proposal_contribution

Revision ID: 3514aaf4648f
Revises: c0646a888d4f
Create Date: 2019-02-21 12:24:15.800835

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import expression


# revision identifiers, used by Alembic.
revision = '3514aaf4648f'
down_revision = 'c0646a888d4f'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal_contribution', sa.Column('staking', sa.Boolean(), nullable=False, server_default=expression.false()))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposal_contribution', 'staking')
    # ### end Alembic commands ###
