"""milestone payment fields

Revision ID: 3793d9a71e27
Revises: 86d300cb6d69
Create Date: 2019-02-11 11:01:44.703413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3793d9a71e27'
down_revision = '86d300cb6d69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestone', sa.Column('accept_arbiter_id', sa.Integer(), nullable=True))
    op.add_column('milestone', sa.Column('date_accepted', sa.DateTime(), nullable=True))
    op.add_column('milestone', sa.Column('date_paid', sa.DateTime(), nullable=True))
    op.add_column('milestone', sa.Column('date_rejected', sa.DateTime(), nullable=True))
    op.add_column('milestone', sa.Column('date_requested', sa.DateTime(), nullable=True))
    op.add_column('milestone', sa.Column('index', sa.Integer(), nullable=False))
    op.add_column('milestone', sa.Column('paid_tx_id', sa.String(length=255), nullable=True))
    op.add_column('milestone', sa.Column('reject_arbiter_id', sa.Integer(), nullable=True))
    op.add_column('milestone', sa.Column('reject_reason', sa.String(length=255), nullable=True))
    op.add_column('milestone', sa.Column('requested_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'milestone', 'user', ['accept_arbiter_id'], ['id'])
    op.create_foreign_key(None, 'milestone', 'user', ['reject_arbiter_id'], ['id'])
    op.create_foreign_key(None, 'milestone', 'user', ['requested_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'milestone', type_='foreignkey')
    op.drop_constraint(None, 'milestone', type_='foreignkey')
    op.drop_constraint(None, 'milestone', type_='foreignkey')
    op.drop_column('milestone', 'requested_user_id')
    op.drop_column('milestone', 'reject_reason')
    op.drop_column('milestone', 'reject_arbiter_id')
    op.drop_column('milestone', 'paid_tx_id')
    op.drop_column('milestone', 'index')
    op.drop_column('milestone', 'date_requested')
    op.drop_column('milestone', 'date_rejected')
    op.drop_column('milestone', 'date_paid')
    op.drop_column('milestone', 'date_accepted')
    op.drop_column('milestone', 'accept_arbiter_id')
    # ### end Alembic commands ###
