"""empty message

Revision ID: 3ffceaeb996a
Revises: 78864f8c5150
Create Date: 2018-12-19 16:27:22.465882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ffceaeb996a'
down_revision = '78864f8c5150'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('proposal_proposal_address_key', 'proposal', type_='unique')
    op.drop_column('proposal', 'proposal_address')
    op.drop_column('proposal', 'trustees')
    op.drop_column('proposal', 'vote_duration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal', sa.Column('vote_duration', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('proposal', sa.Column('trustees', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    op.add_column('proposal', sa.Column('proposal_address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_unique_constraint('proposal_proposal_address_key', 'proposal', ['proposal_address'])
    # ### end Alembic commands ###
