"""Add no_refund column to contributions, default to false

Revision ID: 484abe10e157
Revises: 13365ffe910e
Create Date: 2019-03-13 16:35:01.520404

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import expression


# revision identifiers, used by Alembic.
revision = '484abe10e157'
down_revision = '13365ffe910e'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal_contribution', sa.Column('no_refund', sa.Boolean(), nullable=False, server_default=expression.false()))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposal_contribution', 'no_refund')
    # ### end Alembic commands ###
