"""empty message

Revision ID: 4ca14e6e8976
Revises: 7fea7427e9d6
Create Date: 2019-11-06 12:58:45.503087

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4ca14e6e8976'
down_revision = '7fea7427e9d6'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestone', sa.Column('days_estimated', sa.String(length=255), nullable=True))
    op.alter_column('milestone', 'date_estimated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('milestone', 'date_estimated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('milestone', 'days_estimated')
    # ### end Alembic commands ###
