"""empty message

Revision ID: 515abdefed7a
Revises: 4505f00c4ebd
Create Date: 2019-10-17 16:41:58.519224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '515abdefed7a'
down_revision = '4505f00c4ebd'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposal_subscribers',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposal.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.add_column('proposal', sa.Column('accepted_with_funding', sa.Boolean(), nullable=True))
    op.add_column('proposal', sa.Column('version', sa.String(length=255), nullable=True))
    op.alter_column('proposal', 'deadline_duration',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proposal', 'deadline_duration',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('proposal', 'version')
    op.drop_column('proposal', 'accepted_with_funding')
    op.drop_table('proposal_subscribers')
    # ### end Alembic commands ###
