"""empty message

Revision ID: 5bd3335606c5
Revises: 3ffceaeb996a
Create Date: 2019-01-04 15:34:41.124168

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import Sequence, CreateSequence


# revision identifiers, used by Alembic.
revision = '5bd3335606c5'
down_revision = '3ffceaeb996a'
branch_labels = None
depends_on = None


def upgrade():
    # Handle primary key change
    op.execute('ALTER TABLE proposal_contribution DROP CONSTRAINT proposal_contribution_pkey CASCADE')

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal_contribution', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('proposal_contribution', sa.Column('status', sa.String(length=255), nullable=False))
    op.alter_column('proposal_contribution', 'tx_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('proposal_contribution', 'from_address')
    # ### end Alembic commands ###

    # Recreate primary key
    op.create_primary_key('proposal_contribution_pkey', 'proposal_contribution', ['id'])
    if op._proxy.migration_context.dialect.supports_sequences:
        op.execute(CreateSequence(Sequence('proposal_contribution_sequence')))


def downgrade():
    # Handle primary key change
    op.execute('ALTER TABLE proposal_contribution DROP CONSTRAINT proposal_contribution_pkey CASCADE')
    if op._proxy.migration_context.dialect.supports_sequences:
        op.execute('DROP SEQUENCE proposal_contribution_sequence')

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal_contribution', sa.Column('from_address', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('proposal_contribution', 'tx_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('proposal_contribution', 'status')
    op.drop_column('proposal_contribution', 'id')
    # ### end Alembic commands ###

    # Recreate primary key
    op.create_primary_key('proposal_contribution_pkey', 'proposal_contribution', ['tx_id'])
