"""empty message

Revision ID: 6624244a249e
Revises: 8f8001e98e65
Create Date: 2020-02-10 20:25:34.448725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6624244a249e'
down_revision = '8f8001e98e65'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal', sa.Column('live_draft_parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'proposal', 'proposal', ['live_draft_parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proposal', type_='foreignkey')
    op.drop_column('proposal', 'live_draft_parent_id')
    # ### end Alembic commands ###
