"""empty message

Revision ID: 722b4e7f7a58
Revises: e0d970ed6500
Create Date: 2019-01-28 20:46:13.497530

"""
from alembic import op
import sqlalchemy as sa
from grant.task.models import JsonEncodedDict

# revision identifiers, used by Alembic.
revision = '722b4e7f7a58'
down_revision = 'e0d970ed6500'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.Integer(), nullable=False),
    sa.Column('blob', JsonEncodedDict(), nullable=False),
    sa.Column('execute_after', sa.DateTime(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
