"""empty message

Revision ID: 78864f8c5150
Revises: 13d788130b39
Create Date: 2018-12-13 12:41:27.571421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78864f8c5150'
down_revision = '13d788130b39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_recovery',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_recovery')
    # ### end Alembic commands ###
