"""empty message

Revision ID: 7e39b9773390
Revises: 312db8611967
Create Date: 2018-11-09 16:39:33.571823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e39b9773390'
down_revision = '312db8611967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal', sa.Column('brief', sa.String(length=255), nullable=False, server_default=""))
    op.add_column('proposal', sa.Column('deadline_duration', sa.Integer(), nullable=False, server_default="5184000"))
    op.add_column('proposal', sa.Column('payout_address', sa.String(length=255), nullable=False, server_default=""))
    op.add_column('proposal', sa.Column('status', sa.String(length=255), nullable=False, server_default="LIVE"))
    op.add_column('proposal', sa.Column('target', sa.BigInteger(), nullable=False, server_default="1"))
    op.add_column('proposal', sa.Column('trustees', sa.String(length=1024), nullable=False, server_default=""))
    op.add_column('proposal', sa.Column('vote_duration', sa.Integer(), nullable=False, server_default="604800"))
    op.alter_column('proposal', 'proposal_address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###

    # Remove default value for new columns
    op.alter_column('proposal', 'brief', server_default=None)
    op.alter_column('proposal', 'deadline_duration', server_default=None)
    op.alter_column('proposal', 'payout_address', server_default=None)
    op.alter_column('proposal', 'status', server_default=None)
    op.alter_column('proposal', 'target', server_default=None)
    op.alter_column('proposal', 'trustees', server_default=None)
    op.alter_column('proposal', 'vote_duration', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proposal', 'proposal_address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('proposal', 'vote_duration')
    op.drop_column('proposal', 'trustees')
    op.drop_column('proposal', 'target')
    op.drop_column('proposal', 'status')
    op.drop_column('proposal', 'payout_address')
    op.drop_column('proposal', 'deadline_duration')
    op.drop_column('proposal', 'brief')
    # ### end Alembic commands ###
