"""proposal_arbiter table

Revision ID: 86d300cb6d69
Revises: 310dca400b81
Create Date: 2019-02-08 13:06:39.201691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86d300cb6d69'
down_revision = '310dca400b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposal_arbiter',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('proposal_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('status', sa.String(length=255), nullable=False),
                    sa.ForeignKeyConstraint(['proposal_id'], ['proposal.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_constraint('proposal_arbiter_id_fkey', 'proposal', type_='foreignkey')
    op.drop_column('proposal', 'arbiter_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal', sa.Column('arbiter_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('proposal_arbiter_id_fkey', 'proposal', 'user', ['arbiter_id'], ['id'])
    op.drop_table('proposal_arbiter')
    # ### end Alembic commands ###
