"""empty message

Revision ID: 9d2f7db5b5a6
Revises: 0ba15ddf5053
Create Date: 2019-11-13 17:29:46.810554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d2f7db5b5a6'
down_revision = '0ba15ddf5053'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('tip_jar_address', sa.String(length=255), nullable=True))
    op.add_column('user_settings', sa.Column('tip_jar_view_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'tip_jar_view_key')
    op.drop_column('user_settings', 'tip_jar_address')
    # ### end Alembic commands ###
