"""empty message

Revision ID: bb9c6d733952
Revises: e0d970ed6500
Create Date: 2019-01-27 21:58:45.680009

"""
from alembic import op
import sqlalchemy as sa
from grant.task.models import JsonEncodedDict


# revision identifiers, used by Alembic.
revision = 'bb9c6d733952'
down_revision = 'e0d970ed6500'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('blob', JsonEncodedDict(), nullable=False),
    sa.Column('execute_after', sa.DateTime(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
