"""empty message

Revision ID: bea5c35d0cd6
Revises: 6624244a249e
Create Date: 2020-02-26 13:55:40.484701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bea5c35d0cd6'
down_revision = '6624244a249e'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposal_revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('proposal_archive_id', sa.Integer(), nullable=False),
    sa.Column('changes', sa.Text(), nullable=False),
    sa.Column('revision_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['proposal_archive_id'], ['proposal.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proposal_revision')
    # ### end Alembic commands ###
