"""empty message

Revision ID: c55f96720196
Revises: 9d2f7db5b5a6
Create Date: 2019-11-08 17:34:55.828331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c55f96720196'
down_revision = '9d2f7db5b5a6'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal', sa.Column('tip_jar_address', sa.String(length=255), nullable=True))
    op.add_column('proposal', sa.Column('tip_jar_view_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposal', 'tip_jar_view_key')
    op.drop_column('proposal', 'tip_jar_address')
    # ### end Alembic commands ###
