"""empty message

Revision ID: c78ba6d02534
Revises: 13d788130b39
Create Date: 2018-12-17 14:27:41.927159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c78ba6d02534'
down_revision = '13d788130b39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_media', sa.Column('service', sa.String(length=255), nullable=False))
    op.add_column('social_media', sa.Column('username', sa.String(length=255), nullable=False))
    op.drop_column('social_media', 'social_media_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_media', sa.Column('social_media_link', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('social_media', 'username')
    op.drop_column('social_media', 'service')
    # ### end Alembic commands ###
