"""empty message

Revision ID: d03c91f3038d
Revises: bea5c35d0cd6
Create Date: 2020-12-27 15:48:36.787259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd03c91f3038d'
down_revision = 'bea5c35d0cd6'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal', sa.Column('kyc_approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposal', 'kyc_approved')
    # ### end Alembic commands ###
