"""Adds refund_address to user_settings

Revision ID: ebccb1298297
Revises: 02acd43b4357
Create Date: 2019-02-16 11:37:46.900729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebccb1298297'
down_revision = '02acd43b4357'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('refund_address', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'refund_address')
    # ### end Alembic commands ###
