"""empty message

Revision ID: eddbe541cff1
Revises: e0d970ed6500
Create Date: 2019-01-24 11:20:32.989266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eddbe541cff1'
down_revision = 'e0d970ed6500'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal', sa.Column('contribution_matching', sa.Float(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposal', 'contribution_matching')
    # ### end Alembic commands ###
