enum AuthTypes {
  AUTH_USER = 'AUTH_USER',
  AUTH_USER_PENDING = 'AUTH_USER_PENDING',
  AUTH_USER_FULFILLED = 'AUTH_USER_FULFILLED',
  AUTH_USER_REJECTED = 'AUTH_USER_REJECTED',

  CREATE_USER = 'CREATE_USER',
  CREATE_USER_PENDING = 'CREATE_USER_PENDING',
  CREATE_USER_FULFILLED = 'CREATE_USER_FULFILLED',
  CREATE_USER_REJECTED = 'CREATE_USER_REJECTED',

  CHECK_USER = 'CHECK_USER',
  CHECK_USER_PENDING = 'CHECK_USER_PENDING',
  CHECK_USER_FULFILLED = 'CHECK_USER_FULFILLED',
  CHECK_USER_REJECTED = 'CHECK_USER_REJECTED',

  SIGN_TOKEN = 'AUTH_USER',
  SIGN_TOKEN_PENDING = 'SIGN_TOKEN_PENDING',
  SIGN_TOKEN_FULFILLED = 'SIGN_TOKEN_FULFILLED',
  SIGN_TOKEN_REJECTED = 'SIGN_TOKEN_REJECTED',

  LOGOUT = 'LOGOUT',
  LOGOUT_PENDING = 'LOGOUT_PENDING',
  LOGOUT_FULFILLED = 'LOGOUT_FULFILLED',
  LOGOUT_REJECTED = 'LOGOUT_REJECTED',

  SET_AUTH_FORWARD_LOCATION = 'SET_AUTH_FORWARD_LOCATION',
}

export default AuthTypes;
